const search_data = [{
  key: 1,
  Name: "Dummy_Name_1",
  Price: "1341",
  img_url: "https://2.bp.blogspot.com/-VEcTZ1y-BsA/WlUUlarSrnI/AAAAAAAAJUo/sQMJA4fuNa8yI-NGrMww0rQQhy8ILrHBQCLcBGAs/s1600/DELHI%2BPOTATOES%2B8473%2Bcopy.jpg",
  Address: "Dummy_Address_1",
  Rating: "1",
  Num_Reviews: "346",
  Format: "Lunch-Box",
  Occasion: "Birthday"
  },
  {
  key: 2,
  Name: "Dummy_Name_2",
  Price: "1998",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Indian_food_at_restaurant_in_Paris_-_2020-08-20.jpg/800px-Indian_food_at_restaurant_in_Paris_-_2020-08-20.jpg",
  Address: "Dummy_Address_2",
  Rating: "2",
  Num_Reviews: "337",
  Format: "Mini-Buffet",
  Occasion: "House-party"
  },
  {
  key: 3,
  Name: "Dummy_Name_3",
  Price: "1089",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Vegetarian_Andhra_Meal.jpg/1024px-Vegetarian_Andhra_Meal.jpg",
  Address: "Dummy_Address_3",
  Rating: "3",
  Num_Reviews: "38",
  Format: "Lunch-Box",
  Occasion: "Society-event"
  },
  {
  key: 4,
  Name: "Dummy_Name_4",
  Price: "1744",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Assamese_Thali.jpg/800px-Assamese_Thali.jpg",
  Address: "Dummy_Address_4",
  Rating: "3",
  Num_Reviews: "52",
  Format: "Top-up",
  Occasion: "House-party"
  },
  {
  key: 5,
  Name: "Dummy_Name_5",
  Price: "1890",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/7/79/Bengali_Fish_meal.jpg",
  Address: "Dummy_Address_5",
  Rating: "5",
  Num_Reviews: "104",
  Format: "Lunch-Box",
  Occasion: "Society-event"
  },
  {
  key: 6,
  Name: "Dummy_Name_6",
  Price: "1664",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Palakpaneer.jpg/800px-Palakpaneer.jpg",
  Address: "Dummy_Address_6",
  Rating: "3",
  Num_Reviews: "390",
  Format: "Top-up",
  Occasion: "Baby-shower"
  },
  {
  key: 7,
  Name: "Dummy_Name_7",
  Price: "1633",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Roti_with_Baigan%28Brinjal%29_subji_and_curd.jpg/800px-Roti_with_Baigan%28Brinjal%29_subji_and_curd.jpg",
  Address: "Dummy_Address_7",
  Rating: "4",
  Num_Reviews: "145",
  Format: "Top-up",
  Occasion: "House-warming"
  },
  {
  key: 8,
  Name: "Dummy_Name_8",
  Price: "1676",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Rajma_Chawal%2C_from_India.jpg/800px-Rajma_Chawal%2C_from_India.jpg",
  Address: "Dummy_Address_8",
  Rating: "2",
  Num_Reviews: "45",
  Format: "Top-up",
  Occasion: "Society-event"
  },
  {
  key: 9,
  Name: "Dummy_Name_9",
  Price: "1848",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/2/28/Vindalho.jpg",
  Address: "Dummy_Address_9",
  Rating: "3",
  Num_Reviews: "464",
  Format: "Top-up",
  Occasion: "House-warming"
  },
  {
  key: 10,
  Name: "Dummy_Name_10",
  Price: "1558",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Khaman.jpg/1024px-Khaman.jpg",
  Address: "Dummy_Address_10",
  Rating: "2",
  Num_Reviews: "312",
  Format: "Top-up",
  Occasion: "Baby-shower"
  },
  {
  key: 11,
  Name: "Dummy_Name_11",
  Price: "547",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Sour_cake_%27Handwo%27.jpg/800px-Sour_cake_%27Handwo%27.jpg",
  Address: "Dummy_Address_11",
  Rating: "5",
  Num_Reviews: "484",
  Format: "Buffet",
  Occasion: "Birthday"
  },
  {
  key: 12,
  Name: "Dummy_Name_12",
  Price: "1375",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Rogan_josh02.jpg",
  Address: "Dummy_Address_12",
  Rating: "4",
  Num_Reviews: "80",
  Format: "Mini-Buffet",
  Occasion: "Birthday"
  },
  {
  key: 13,
  Name: "Dummy_Name_13",
  Price: "1197",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Another_Vegetarian_Meal.jpg/800px-Another_Vegetarian_Meal.jpg",
  Address: "Dummy_Address_13",
  Rating: "2",
  Num_Reviews: "241",
  Format: "Mini-Buffet",
  Occasion: "Baby-shower"
  },
  {
  key: 14,
  Name: "Dummy_Name_14",
  Price: "1163",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Bisi_Bele_Bath.jpg/800px-Bisi_Bele_Bath.jpg",
  Address: "Dummy_Address_14",
  Rating: "5",
  Num_Reviews: "229",
  Format: "Buffet",
  Occasion: "House-party"
  },
  {
  key: 15,
  Name: "Dummy_Name_15",
  Price: "1444",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Keralacuisinefish.jpg",
  Address: "Dummy_Address_15",
  Rating: "3",
  Num_Reviews: "472",
  Format: "Top-up",
  Occasion: "Society-event"
  },
  {
  key: 16,
  Name: "Dummy_Name_16",
  Price: "856",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Fish_Moilee_Kerala_Style_%28aka_KeralaFish_Molly%29.JPG/800px-Fish_Moilee_Kerala_Style_%28aka_KeralaFish_Molly%29.JPG",
  Address: "Dummy_Address_16",
  Rating: "4",
  Num_Reviews: "378",
  Format: "Lunch-Box",
  Occasion: "House-party"
  },
  {
  key: 17,
  Name: "Dummy_Name_17",
  Price: "1342",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Baati.jpg/800px-Baati.jpg",
  Address: "Dummy_Address_17",
  Rating: "3",
  Num_Reviews: "251",
  Format: "Food-Trucks",
  Occasion: "Baby-shower"
  },
  {
  key: 18,
  Name: "Dummy_Name_18",
  Price: "1027",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Thukpa%2C_Manali%2C_Himachal_Pradesh.JPG/800px-Thukpa%2C_Manali%2C_Himachal_Pradesh.JPG",
  Address: "Dummy_Address_18",
  Rating: "2",
  Num_Reviews: "153",
  Format: "Mini-Buffet",
  Occasion: "House-party"
  },
  {
  key: 19,
  Name: "Dummy_Name_19",
  Price: "1217",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/6/63/Pav_Bhaji.jpg",
  Address: "Dummy_Address_19",
  Rating: "5",
  Num_Reviews: "327",
  Format: "Top-up",
  Occasion: "House-warming"
  },
  {
  key: 20,
  Name: "Dummy_Name_20",
  Price: "1953",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Cooked_Poha.jpg/1024px-Cooked_Poha.jpg",
  Address: "Dummy_Address_20",
  Rating: "3",
  Num_Reviews: "233",
  Format: "Top-up",
  Occasion: "House-warming"
  },
  {
  key: 21,
  Name: "Dummy_Name_21",
  Price: "872",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Chickentandoori.jpg",
  Address: "Dummy_Address_21",
  Rating: "5",
  Num_Reviews: "408",
  Format: "Mini-Buffet",
  Occasion: "House-party"
  },
  {
  key: 22,
  Name: "Dummy_Name_22",
  Price: "1566",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Rajasthanthali.jpg/800px-Rajasthanthali.jpg",
  Address: "Dummy_Address_22",
  Rating: "1",
  Num_Reviews: "290",
  Format: "Food-Trucks",
  Occasion: "Birthday"
  },
  {
  key: 23,
  Name: "Dummy_Name_23",
  Price: "567",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Dosai_Chutney_Hotel_Saravana_Bhavan.jpg/800px-Dosai_Chutney_Hotel_Saravana_Bhavan.jpg",
  Address: "Dummy_Address_23",
  Rating: "1",
  Num_Reviews: "46",
  Format: "Mini-Buffet",
  Occasion: "Baby-shower"
  },
  {
  key: 24,
  Name: "Dummy_Name_24",
  Price: "918",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Thukpa%2C_Tibetan_noodle_in_Osaka%2C_Japan.jpg/800px-Thukpa%2C_Tibetan_noodle_in_Osaka%2C_Japan.jpg",
  Address: "Dummy_Address_24",
  Rating: "3",
  Num_Reviews: "242",
  Format: "Mini-Buffet",
  Occasion: "House-warming"
  },
  {
  key: 25,
  Name: "Dummy_Name_25",
  Price: "605",
  img_url: "https://upload.wikimedia.org/wikipedia/commons/4/49/Vegetarian_Curry.jpeg",
  Address: "Dummy_Address_25",
  Rating: "2",
  Num_Reviews: "302",
  Format: "Lunch-Box",
  Occasion: "Society-event"
  },
  {
  key: 26,
  Name: "Dummy_Name_26",
  Price: "1185",
  img_url: "https://sukhis.com/wp-content/uploads/2017/06/Appetizers.jpg",
  Address: "Dummy_Address_26",
  Rating: "1",
  Num_Reviews: "189",
  Format: "Food-Trucks",
  Occasion: "Birthday"
  },
  {
  key: 27,
  Name: "Dummy_Name_27",
  Price: "1685",
  img_url: "https://sukhis.com/wp-content/uploads/2017/06/IndianBread.jpg",
  Address: "Dummy_Address_27",
  Rating: "5",
  Num_Reviews: "479",
  Format: "Lunch-Box",
  Occasion: "Society-event"
  },
  {
  key: 28,
  Name: "Dummy_Name_28",
  Price: "1328",
  img_url: "https://sukhis.com/wp-content/uploads/2018/10/shutterstock_620407940-768x512.jpg",
  Address: "Dummy_Address_28",
  Rating: "2",
  Num_Reviews: "412",
  Format: "Food-Trucks",
  Occasion: "Birthday"
  },
  {
  key: 29,
  Name: "Dummy_Name_29",
  Price: "1382",
  img_url: "https://2.bp.blogspot.com/-VEcTZ1y-BsA/WlUUlarSrnI/AAAAAAAAJUo/sQMJA4fuNa8yI-NGrMww0rQQhy8ILrHBQCLcBGAs/s1600/DELHI%2BPOTATOES%2B8473%2Bcopy.jpg",
  Address: "Dummy_Address_29",
  Rating: "3",
  Num_Reviews: "200",
  Format: "Lunch-Box",
  Occasion: "Birthday"
  },
  {
  key: 30,
  Name: "Dummy_Name_30",
  Price: "1744",
  img_url: "http://4.bp.blogspot.com/-7kg6ZPEzZMo/UFhr2KNQPcI/AAAAAAAABBQ/22gEAY9hK_M/s1600/Venkij+food+blog+image.jpg",
  Address: "Dummy_Address_30",
  Rating: "3",
  Num_Reviews: "15",
  Format: "Food-Trucks",
  Occasion: "House-party"
  }
  ];
export default search_data;
